module.exports = {
  noJumpingHeaders: require('./no-jumping-headers'),
  noFormattingTags: require('./no-formatting-tags'),
  hasAlt: require('./has-alt'),
  empty: require('./no-empty-links-and-buttons'),
  placeholderHasLabel: require('./placeholder-has-label'),
  htmlHasLang: require('./html-has-lang'),
  mouseEventsWithoutKeyEvents: require('./mouseevents-without-keyevents'),
  headingHasContent: require('./heading-has-content'),
  clickWithKeyboardEvent: require('./click-with-key-event'),
  ariaUnsupportedElements: require('./aria-unsupported-elements'),
  noAudioAutoplay: require('./no-audio-autoplay'),
  pageHasTitle: require('./page-has-title'),
  noDuplicatedAttributes: require('./no-duplicated-attributes'),
  unclickableWithoutRole: require('./unclickable-without-role'),
  noPositiveTabindex: require('./no-positive-tabindex'),
  labelHasFor: require('./label-has-for'),
  linksHasUrl: require('./links-has-url.js'),
  controlsFormWrapped: require('./controls-form-wrapped'),
  tabpanelWrappedInTablist: require('./tabpanel-wrapped-in-tablist')
};
